name: Release
run-name: Release ${{ github.ref_name }} by @${{ github.actor }}

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
  # Run manually
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  VERGEN_IDEMPOTENT: true
  AWS_LC_SYS_PREBUILT_NASM: 1

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
  upload-assets:
    name: Binary
    needs: [ create-release ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: mdbook-graphql-playground
          target: ${{ matrix.target }}
          include: CHANGELOG.md,CODE_OF_CONDUCT.md,CONTRIBUTING.md,LICENSE.md,README.md
          tar: unix
          zip: windows
          leading_dir: true
          token: ${{ secrets.GITHUB_TOKEN }}
  crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-workspaces
      - run: cargo publish --from-git
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
