name: Remove Labels

on:
  issues:
    types: [ closed ]
  pull_request:
    types: [ closed ]

jobs:
  remove_labels:
    runs-on: ubuntu-22.04
    steps:
      - name: Remove labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "triage, good first issue, help wanted, question"
